version: '3.8'

services:
  rebeca:
    image: alberth121484/rebeca-py:01.00.001
    container_name: rebeca
    restart: unless-stopped
    stop_grace_period: 30s
    networks:
      - tiendasneto
    environment:
      # Slack Configuration
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      
      # Application Configuration
      - PORT=3000
      - TZ=America/Mexico_City
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.rebeca.rule=Host(`rebeca.tiendasnetows.com`)
        - traefik.http.routers.rebeca.entrypoints=websecure
        - traefik.http.routers.rebeca.priority=1
        - traefik.http.routers.rebeca.tls.certresolver=letsencryptresolver
        - traefik.http.routers.rebeca.service=rebeca
        - traefik.http.services.rebeca.loadbalancer.server.port=3000
        - traefik.http.services.rebeca.loadbalancer.passHostHeader=1
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  tiendasneto:
    external: true
    name: tiendasneto